#配置数据源的属性
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://114.55.92.94:3306/deao?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  #thymeleaf的配置
  thymeleaf: 
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置
shiro:
  anon-urls:
    - /index.html*
    - /public/login*
    - /login/login*
    - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
    - /**
server:
  port: 9090